services:
    mongo:
        image: mongo:6.0
        ports:
            - 27017:27017
        networks:
            - dev-network
        volumes:
            - proxy-data:/data/db

    proxy:
        image: proxy-dev
        links:
            - mongo
        depends_on:
            - mongo
        networks:
            - dev-network
        ports:
            - 8004:8004
        env_file:
            - proxy-env.env

volumes:
  proxy-data:
    external: true

networks:
  dev-network:
    driver: bridge