version: '3'
services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
      environment:
        - 'node.name=BAE'
        - 'discovery.type=single-node'
        - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      ports:
          - "127.0.0.1:9200:9200"
      networks:
        main:
          aliases:
            - elastic.docker

    mongo:
        image: mongo:4.4
        ports:
            - 27017:27017
        networks:
            main:
        volumes:
            - ./proxy-data:/data/db

    proxy:
        image: proxy-dev
        links:
            - mongo
        depends_on:
            - mongo
        ports:
            - 8004:8004
        networks:
            main:
                aliases:
                    - proxy.docker
        volumes:
            - ../:/business-ecosystem-logic-proxy

networks:
    main:
        external: true
