name: Publish

on:
  release:
    types: [released]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get release tag
        id: get_release
        run: echo ::set-output name=RELEASE_TAG::${GITHUB_REF#refs/tags/}

      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          tags: |
            fiware/biz-ecosystem-logic-proxy:${{ steps.get_release.outputs.RELEASE_TAG }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}